Estudy_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# TEMPLATE TAGGING

urlpatterns = [
    path("", include("HomePage.urls")),
    path("acoounts/", include("django.contrib.auth.urls")),
    path("register/", include("accounts.urls")),
    path("admin/", admin.site.urls, name="admin-site-url"),
    path("details/", include("DetailsAccount.urls")),
    path("category/", include("category.urls")),
    path("forum/", include("forum.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("youtube/", include("YouTube.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomePage/urls.py
from django.urls import path, include
from . import views


app_name = "HomePage"

urlpatterns = [
    path("", views.indexView.as_view(), name="home"),
    path("about/", views.aboutView.as_view(), name="about"),
    path("Delete/<post_id>", views.deletePost, name="delete-post"),
    path("update/<post_id>", views.updatePost, name="update-post"),
    path("search/", views.searchView.as_view(), name="search-user"),
    path("down/<int:user_id>", views.DownPermissions.as_view(), name="down-per"),
    path("<int:user_id>", views.UpPermissions.as_view(), name="up-per"),
]

accounts/urls.py
from django.urls import path


from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signUp, name="signup"),
    path("signupStudent/", views.signStudentView.as_view(), name="si-student"),
    path("signupLecture/", views.signLectureView.as_view(), name="si-lecture"),
    # path('login/', views.LogInView.as_view(), name='logIn'),
]

forum/urls.py
from django.urls import path
from forum import views

app_name = "Forum"

urlpatterns = [
    path("", views.forumView.as_view(), name="forum-main"),
    path("<user_id>", views.forumView.as_view(), name="post-post"),
    path("<user_id>/<post_id>", views.PostComments, name="comment-post"),
    path("delete/<int:post_id>/", views.DeletePost, name="delete-po"),
    path("delComment/<int:comment_id>/", views.DeleteComment, name="delete-co"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from gridfs_storage.storage import GridFSStorage
from imagekitio import ImageKit
imagekit = ImageKit(
    private_key='private_0InZG7wQykta/PjGyhg2Nk14fAw=',
    public_key='public_wI6Gnx1NNvSxeDBJlqi27qErJO8=',
    url_endpoint='https://ik.imagekit.io/zyae7okkm'
)

DEPARTMENT_CHOICES = (
    ("1", "הנדסת תוכנה"),
    ("2", "הנדסת בניין"),
    ("3", "הנדסת מכונות"),
    ("4", "הנדסת חשמל"),
    ("5", "הנדסה כימית"),
)

YEAR_CHOICES = (
    ("1", "שנה א"),
    ("2", "שנה ב"),
    ("3", "שנה ג"),
    ("4", "שנה ד"),
)

SEMESTER_CHOICES = (
    ("1", "סמסטר א"),
    ("2", "סמסטר ב"),
    ("3", "סמסטר קיץ"),
)


def get_profile_pic():
    x = '628b203c55084aedc16cea42'
    details = imagekit.get_file_details(x)
    return str(details['response']['name'])

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    permissions = models.BooleanField(default=True)
    imag_profile = models.ImageField(
        upload_to="images_profiles", null=True, default=get_profile_pic(), storage=GridFSStorage(base_url="https://ik.imagekit.io/zyae7okkm/")
    )


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    Phone = PhoneNumberField()
    ID = models.CharField(max_length=10, null=True)
    department = models.CharField(
        max_length=30, choices=DEPARTMENT_CHOICES, default="1"
    )
    year = models.CharField(max_length=10, choices=YEAR_CHOICES, default="1")
    semester = models.CharField(max_length=15, choices=SEMESTER_CHOICES, default="1")

    def __str__(self):
        return str(self.user.username)


class Lecturer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    Phone = PhoneNumberField()
    ID = models.CharField(max_length=9, null=True)

    def __str__(self):
        return str(self.user.username)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login

from .form import StudentUserCreationForm, LecturerUserCreationForm

# Create your views here.

# class signStudentView(CreateView):
#     model = User
#     form_class = StudentUserCreationForm
#     template_name = "accounts/signupStudent.html"


#     def form_invalid(self, form):
#       user = form.save()
#       login(self.request, user)
#       return redirect("HomePage:home")


class signStudentView(View):
    def get(self, request):
        form = StudentUserCreationForm()
        context = {
            "form": form,
        }
        return render(request, "accounts/signupStudent.html", context)

    def post(self, request):
        form = StudentUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("Details:d-s", user.id)
        else:
            return render(request, "accounts/signupStudent.html", {"form": form})


class signLectureView(View):
    def get(self, request):
        form = LecturerUserCreationForm()
        return render(request, "accounts/signupLecture.html", {"form": form})

    def post(self, request):
        form = LecturerUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("Details:d-l", user.id)
        else:
            return render(request, "accounts/signupLecture.html", {"form": form})


def signUp(request):
    return render(request, "accounts/signup.html")

templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
<style>
  .form-title{
    padding: 30px;
    text-align: center;
  }
  .signup-form {
    margin-left: 20px;
    margin-right: 75px;
    padding-left: 34px;
  }
      
</style>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>SignUp Estudy </title>
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static "fonts/material-icon/css/material-design-iconic-font.min.css" %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    <!-- Main css -->
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
  </head>
  <body>
    {% block bodyOfsign %}
    <div class="main">
      <!-- Sign up form -->
      <section class="signup">
        <div class="container">
          <div class="signup-content">
            <div class="signup-form">
              <h2 class="form-title">Sign up</h2>
              <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <a href="{% url 'accounts:si-student' %}" class="signup-image-link">Are you a student? Press Here</a>
                </div>
                <div class="form-group">
                  <a href= "{% url 'accounts:si-lecture' %}" class="signup-image-link">Are you a lecture? Press Here</a>
                </div>
                <div class="form-group">
                  <a href= {% url 'HomePage:home' %} class="signup-image-link">Home page</a>
                </div>
                <div class="form-group">
                  <a href= {% url 'login' %} class="signup-image-link">I am already member</a>
                </div>
  
            </div>
            <div class="signup-image">
              <figure>
                <img src="{% static "images/signup-image.jpg" %}" alt="sing up image" />
              </figure>
            </div>
          </div>
        </div>
      </section>
    <!-- JS -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}" ></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </script>
    {% endblock bodyOfsign %} 
  </body>
</html>

templates/accounts/signupLecture.html
{% extends 'accounts/signup.html' %}

{% load static %}


{% block bodyOfsign %}

<div class="main">

  <!-- Sign up form -->
  <section class="signup">
      <div class="container">
          <div class="signup-content">
              <div class="signup-form" style="
                margin-left: 27px;
                margin-right: 75px;
                padding-left: 34px;">
                  <h2 class="form-title">Sign up Lecture</h2>
                  <form method="POST" class="register-form" id="register-form">
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="name"><br><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.username.label}} 
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        <label for="email"><br><i class="zmdi zmdi-email"></i></label>
                        {{form.email.label}}  
                        {{form.email}} 
                    </div>
                    <div class="form-group">
                        <label for="pass"><br><i class="zmdi zmdi-lock"></i></label>
                        {{form.password1.label}}                     
                        {{form.password1}}                     
                       </div>
                    <div class="form-group">
                        <label for="re-pass"><br><i class="zmdi zmdi-lock-outline"></i></label>
                        {{form.password2.label}}
                        {{form.password2}}
                    </div>
                    <div class="form-group">
                        {{form.captcha}}
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <p class=" label label-danger">{{form.errors.username}}</p>
                        <p class=" label label-danger">{{form.errors.email}}</p>
                        <p class=" label label-danger">{{form.errors.password2}}</p>
                        <p class=" label label-danger">{{form.captcha}}</p>
                    </div>
                    {% endif %}
                    <div class="form-group form-button">
                        <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                    </div>
                  </form>
              </div>
              <div class="signup-image">
                  <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                  <a href= {% url 'login' %} class="signup-image-link">I am already member</a>
                  <a href= {% url 'HomePage:home' %} class="signup-image-link">Home page</a>

              </div>
          </div>
      </div>
  </section>


{% endblock  %}

templates/accounts/signupStudent.html
{% extends 'accounts/signup.html' %}

{% load static %}


{% block bodyOfsign %}

<div class="main">

  <!-- Sign up form -->
  <section class="signup">
      <div class="container">
          <div class="signup-content">
              <div class="signup-form" style="
                margin-left: 27px;
                margin-right: 75px;
                padding-left: 34px;">
                  <h2 class="form-title">Sign up Student</h2>
                  <form method="POST" class="register-form" id="register-form">
                    {% csrf_token %}
                      <div class="form-group">
                          <label for="name"><br><i class="zmdi zmdi-account material-icons-name"></i></label>
                          {{form.username.label}} 
                          {{form.username}}
                      </div>
                      <div class="form-group">
                          <label for="email"><br><i class="zmdi zmdi-email"></i></label>
                          {{form.email.label}}  
                          {{form.email}} 
                      </div>
                      <div class="form-group">
                          <label for="pass"><br><i class="zmdi zmdi-lock"></i></label>
                          {{form.password1.label}}                     
                          {{form.password1}}                     
                         </div>
                      <div class="form-group">
                          <label for="re-pass"><br><i class="zmdi zmdi-lock-outline"></i></label>
                          {{form.password2.label}}
                          {{form.password2}}
                      </div>
                      <div class="form-group">
                        {{form.captcha}}
                     </div>
                      {% if form.errors %}
                      <div class="alert alert-danger">
                          <p class=" label label-danger">{{form.errors.username}}</p>
                          <p class=" label label-danger">{{form.errors.email}}</p>
                          <p class=" label label-danger">{{form.errors.password2}}</p>
                      </div>
                      {% endif %}
                      <div class="form-group form-button">
                          <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                      </div>
                  </form>
              </div> 
              <div class="signup-image">
                  <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                  <a href= {% url 'login' %} class="signup-image-link">I am already member</a>
                  <a href= {% url 'HomePage:home' %} class="signup-image-link">Home page</a>

              </div>
          </div>
      </div>
  </section>


{% endblock  %}

templates/accounts/update.html
{% extends 'base.html' %}

{% block links %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
{% endblock %}




{% block style %}
  <style>
  .msg-form {
      background-color: white;
      padding: 20px
  }
  
  .pad-icon {
      padding-top: 30px;
      padding-left: 20px
  }
  
  .pad-icon a {
      text-decoration: none;
      margin-right: 40px
  }
  
  .input-group input:focus {
      border: 1px solid blue
  }
  
  .pad-icon a:active {
      height: 30px;
      width: 30px;
      background-color: #0080ff;
      border-radius: 100%
  }
  
  .UpdateCl{
    margin: auto;
    mar
  }

  .links {
      padding-top: 50px;
      width: 50%
  }
  @media (min-width: 576px){
    .col-sm-6 {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 50%;
        margin: auto;
        margin-top: 80px;
        flex: 0 0 50%;
        max-width: 50%;
    }
  }
  @media(min-width:568px) {
      .container-fluid {
          margin: auto;
          width: 96%;
      }
  }
  
  </style>
{% endblock style %}
  



{% block content %}
  <div class="col-sm-6 pad">
    <form class="rounded msg-form" method="POST">
        {% csrf_token %}
        <div class="form-group"> 
          <label for="name" class="h6">Title</label>
            <div class="input-group border rounded">
                <div class="input-group-addon px-2 pt-1">
                    <p class="fa fa-user-o text-primary"></p>
                </div> 
                {{form.title}}
            </div>
        </div>
        <div class="form-group"> 
          <label for="msg" class="h6">Message</label> 
           {% comment %} <textarea name="message" id="msgus" cols="10" rows="5" class="form-control bg-light" placeholder="Message"></textarea>  {% endcomment %}
          {{form.description}}
        </div>
        <div class="form-group d-flex justify-content-end"> 
          <input type="submit" class="btn btn-primary text-white" value="Update"> 
        </div>
    </form>
  </div>
{% endblock %}