DetailsAccount/urls.py
from django.urls import path
from DetailsAccount import views

app_name = "Details"

urlpatterns = [
    path("detailsStudent/<student_id>", views.DetailsStudentView.as_view(), name="d-s"),
    path(
        "detailsLecturer/<lecturer_id>", views.DetailsLectureView.as_view(), name="d-l"
    ),
    path("Delete/<user_id>", views.deleteUser, name="delete-user"),
    path("changePassword/<user_id>", views.ChangeStudentPass.as_view(), name="ch-pass"),
]

Estudy_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# TEMPLATE TAGGING

urlpatterns = [
    path("", include("HomePage.urls")),
    path("acoounts/", include("django.contrib.auth.urls")),
    path("register/", include("accounts.urls")),
    path("admin/", admin.site.urls, name="admin-site-url"),
    path("details/", include("DetailsAccount.urls")),
    path("category/", include("category.urls")),
    path("forum/", include("forum.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("youtube/", include("YouTube.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomePage/urls.py
from django.urls import path, include
from . import views


app_name = "HomePage"

urlpatterns = [
    path("", views.indexView.as_view(), name="home"),
    path("about/", views.aboutView.as_view(), name="about"),
    path("Delete/<post_id>", views.deletePost, name="delete-post"),
    path("update/<post_id>", views.updatePost, name="update-post"),
    path("search/", views.searchView.as_view(), name="search-user"),
    path("down/<int:user_id>", views.DownPermissions.as_view(), name="down-per"),
    path("<int:user_id>", views.UpPermissions.as_view(), name="up-per"),
]

forum/urls.py
from django.urls import path
from forum import views

app_name = "Forum"

urlpatterns = [
    path("", views.forumView.as_view(), name="forum-main"),
    path("<user_id>", views.forumView.as_view(), name="post-post"),
    path("<user_id>/<post_id>", views.PostComments, name="comment-post"),
    path("delete/<int:post_id>/", views.DeletePost, name="delete-po"),
    path("delComment/<int:comment_id>/", views.DeleteComment, name="delete-co"),
]

DetailsAccount/models.py
from django.db import models

# Create your models here.

DetailsAccount/views.py
from django.shortcuts import render, redirect
from django.views import View
from accounts.models import Student, Lecturer, User
from DetailsAccount.form import StudentForm, UserUpdate, LecturerForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
import base64
from imagekitio import ImageKit
imagekit = ImageKit(
    private_key='private_0InZG7wQykta/PjGyhg2Nk14fAw=',
    public_key='public_wI6Gnx1NNvSxeDBJlqi27qErJO8=',
    url_endpoint='https://ik.imagekit.io/zyae7okkm'
)
# Create your views here.


class DetailsStudentView(View):
    def get(self, request, student_id):
        student = Student.objects.get(pk=student_id)
        userStudent = User.objects.get(pk=student_id)
        print(userStudent.imag_profile)
        form_student = StudentForm(request.POST or None, instance=student)
        form_user = UserUpdate(None, instance=userStudent)
        return render(
            request, "details.html", {"form": form_student, "form_user": form_user}
        )

    def post(self, request, student_id):
        form_student = StudentForm(request.POST, request.FILES)
        if form_student.is_valid():
            first_name = form_student.cleaned_data["first_name"]
            last_name = form_student.cleaned_data["last_name"]
            user = User.objects.get(pk=student_id)
            email = form_student.cleaned_data["email"]
            user.first_name = first_name
            user.last_name = last_name
            img = request.FILES.get("imag_profile")
            if img != None:
                imagekit_url = imagekit.upload_file(
                                    file =  base64.b64encode(img.read()), # required
                                    file_name= img.name, # required
                                )
                user.imag_profile = imagekit_url['response']['name']
            user.save()
            student = Student.objects.get(pk=student_id)
            student.first_name = first_name
            student.last_name = last_name
            student.Phone = form_student.cleaned_data["Phone"]
            student.ID = form_student.cleaned_data["ID"]
            student.department = form_student.cleaned_data["department"]
            student.year = form_student.cleaned_data["year"]
            student.semester = form_student.cleaned_data["semester"]

            student.save()
            return redirect("HomePage:home")
        userStudent = User.objects.get(pk=student_id)
        form_user = UserUpdate(None, instance=userStudent)
        return render(
            request, "details.html", {"form": form_student, "form_user": form_user}
        )


class ChangeStudentPass(View):
    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        form_user = UserUpdate(None, instance=user)
        return render(request, "changePass.html", {"form_user": form_user})

    def post(self, request, user_id):
        form = UserUpdate(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=user_id)
            pasw = form.cleaned_data["password"]
            user.set_password(pasw)
            user.save()
            user = authenticate(username=user.username, password=pasw)
            login(request, user)
            return redirect("HomePage:home")
        else:
            return render(request, "changePass.html", {"form_user": form})


# ----------------------------------------------------------------------------------------------------------------------------------------------------


class DetailsLectureView(View):
    def get(self, request, lecturer_id):
        lecturer = Lecturer.objects.get(pk=lecturer_id)
        userLecturer = User.objects.get(pk=lecturer_id)
        form_lecturer = LecturerForm(request.POST or None, instance=lecturer)
        form_user = UserUpdate(None, instance=userLecturer)
        return render(
            request, "details.html", {"form": form_lecturer, "form_user": form_user}
        )

    def post(self, request, lecturer_id):
        form_lecturer = LecturerForm(request.POST, request.FILES)
        if form_lecturer.is_valid():
            first_name = form_lecturer.cleaned_data["first_name"]
            last_name = form_lecturer.cleaned_data["last_name"]
            user = User.objects.get(pk=lecturer_id)
            email = form_lecturer.cleaned_data["email"]
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            img = request.FILES.get("imag_profile")  
            print(img)    
            if img != None:
                imagekit_url = imagekit.upload_file(
                                    file =  base64.b64encode(img.read()), # required
                                    file_name= img.name, # required
                                )
                user.imag_profile = imagekit_url['response']['name']
            user.save()
            lecturer = Lecturer.objects.get(pk=lecturer_id)
            lecturer.first_name = first_name
            lecturer.last_name = last_name
            lecturer.Phone = form_lecturer.cleaned_data["Phone"]
            lecturer.ID = form_lecturer.cleaned_data["ID"]
            lecturer.save()
            return redirect("HomePage:home")
        userLecturer = User.objects.get(pk=lecturer_id)
        form_user = UserUpdate(None, instance=userLecturer)
        return render(
            request, "details.html", {"form": form_lecturer, "form_user": form_user}
        )


def deleteUser(request, user_id):
    user = User.objects.get(pk=user_id)
    user.delete()
    return redirect("HomePage:home")

DetailsAccount/templates/changePass.html
{% extends 'base.html' %}

{% block links %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
{% endblock  %}

{% block style %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');

  * {
      margin: 0;
      padding: 0;
      box-sizing: border-box
  }

  body {
      font-family: 'Poppins', sans-serif;
      background-color: aliceblue
  }

  .wrapper {
      padding: 30px 50px;
      border: 1px solid #ddd;
      border-radius: 15px;
      margin: 10px auto;
      max-width: 600px
  }

  h4 {
      letter-spacing: -1px;
      font-weight: 400
  }

  .img {
      width: 70px;
      height: 70px;
      border-radius: 6px;
      object-fit: cover
  }

  #img-section p,
  #deactivate p {
      font-size: 12px;
      color: #777;
      margin-bottom: 10px;
      text-align: justify
  }

  #img-section b,
  #img-section button,
  #deactivate b {
      font-size: 14px
  }

  label {
      margin-bottom: 0;
      font-size: 14px;
      font-weight: 500;
      color: #777;
      padding-left: 3px
  }

  .form-control {
      border-radius: 10px
  }

  input[placeholder] {
      font-weight: 500
  }

  .form-control:focus {
      box-shadow: none;
      border: 1.5px solid #0779e4
  }

  select {
      display: block;
      width: 100%;
      border: 1px solid #ddd;
      border-radius: 10px;
      height: 40px;
      padding: 5px 10px
  }

  select:focus {
      outline: none
  }

  .button {
      background-color: #fff;
      color: #0779e4
  }

  .button:hover {
      background-color: #0779e4;
      color: #fff
  }

  .btn-primary {
      background-color: #0779e4
  }

  .danger {
      background-color: #fff;
      color: #e20404;
      border: 1px solid #ddd
  }

  .danger:hover {
      background-color: #e20404;
      color: #fff
  }
  .col-md-6{
    text-align: left;
  }

  @media(max-width:576px) {
      .wrapper {
          padding: 25px 20px
      }

      #deactivate {
          line-height: 18px
      }
  }

  .changePass{
    position: relative;
    left: 100px;
  }
</style>
{% endblock style %}


{% block content %}
<form method="post">
    <div class="wrapper bg-white mt-sm-5">
        <h4 class="pb-4 border-bottom">Account settings</h4>
        <div class="py-2">
          {% csrf_token %}
            <div class="row py-2">
                <div class="col-md-6"> 
                    <label for="newPass"><b>New Password</b></label> 
                    {{form_user.password}} 
                </div>
                <div class="col-md-6 pt-md-0 pt-3"> 
                    <label for="oldPass"><b>Confrim Password</b></label>
                    {{form_user.confirm_password}}
                    {% if form_user.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{form_user.confirm_password.errors}}
                      </div>
                    {% endif %}
                </div>
            </div>
    </form>
            <div class="py-3 pb-4 border-bottom"> 
                <button class="btn btn-primary mr-3">Save Changes</button> 
                <a href="{% url 'HomePage:home'%}" class="btn border button">Cancel</a>
                <a href="{% url 'Details:d-s' request.user.id%}" class="changePass">חזרה</a>
            </div>
{% endblock %}

DetailsAccount/templates/details.html
{% extends 'base.html' %}

{% block links %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
{% endblock  %}

{% block style %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');

  * {
      margin: 0;
      padding: 0;
      box-sizing: border-box
  }

  body {
      font-family: 'Poppins', sans-serif;
      background-color: aliceblue
  }

  .wrapper {
      padding: 30px 50px;
      border: 1px solid #ddd;
      border-radius: 15px;
      margin: 10px auto;
      max-width: 600px
  }

  h4 {
      letter-spacing: -1px;
      font-weight: 400
  }

  .img {
      width: 70px;
      height: 70px;
      border-radius: 6px;
      object-fit: cover
  }

  #img-section p,
  #deactivate p {
      font-size: 12px;
      color: #777;
      margin-bottom: 10px;
      text-align: justify
  }

  #img-section b,
  #img-section button,
  #deactivate b {
      font-size: 14px
  }

  label {
      margin-bottom: 0;
      font-size: 14px;
      font-weight: 500;
      color: #777;
      padding-left: 3px
  }

  .form-control {
      border-radius: 10px
  }

  input[placeholder] {
      font-weight: 500
  }

  .form-control:focus {
      box-shadow: none;
      border: 1.5px solid #0779e4
  }

  select {
      display: block;
      width: 100%;
      border: 1px solid #ddd;
      border-radius: 10px;
      height: 40px;
      padding: 5px 10px
  }

  select:focus {
      outline: none
  }

  .button {
      background-color: #fff;
      color: #0779e4
  }

  .button:hover {
      background-color: #0779e4;
      color: #fff
  }

  .btn-primary {
      background-color: #0779e4
  }

  .danger {
      background-color: #fff;
      color: #e20404;
      border: 1px solid #ddd
  }

  .danger:hover {
      background-color: #e20404;
      color: #fff
  }
  .col-md-6{
    text-align: right;
  }

  @media(max-width:576px) {
      .wrapper {
          padding: 25px 20px
      }

      #deactivate {
          line-height: 18px
      }
  }

  .changePass{
    position: relative;
    left: 100px;
  }
</style>
{% endblock style %}


{% block content %}
<form method = "post" enctype="multipart/form-data">
    <div class="wrapper bg-white mt-sm-5">
        <h4 class="pb-4 border-bottom">Account settings</h4>
        <div class="d-flex align-items-start py-3 border-bottom"> 
            {% csrf_token %}
            <img src="https://images.pexels.com/photos/1037995/pexels-photo-1037995.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="img" alt="">
            <div class="pl-sm-4 pl-2" id="img-section"> 
                <label for="photo"><b>Profile Photo</b></label>
                <p>Accepted file type .png. Less than 1MB</p> 
                {{form_user.imag_profile}}
            </div>
        </div>
        <div class="py-2">
            <div class="row py-2">
                <div class="col-md-6"> 
                    <label for="first_name">שם פרטי</label> 
                    {{form.first_name}} 
                </div>
                <div class="col-md-6 pt-md-0 pt-3"> 
                    <label for="last_name">שם משפחה</label>
                    {{form.last_name}}
                </div>
            </div>
            <div class="row py-2">
                <div class="col-md-6"> 
                    <label for="email">מייל המכללה</label> 
                    {{form_user.email}}
                    {% if form_user.email.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form_user.email.errors}}
                    </div>
                    {% endif %}    
                </div>
                <div class="col-md-6 pt-md-0 pt-3"> 
                    <label for="Phone">מספר פלאפון</label>  
                    {{form.Phone}}
                    {% if form.Phone.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{form.Phone.errors}}
                    </div>
                    {% endif %}    
                </div>
            </div>
            <div class="row py-2">
                <div class="col-md-6"> 
                    <label for="ID">תעודת זהות</label> 
                    {{form.ID}}
                   {% if form.ID.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{form.ID.errors}}
                      </div>
                    {% endif %} 
                </div> 
                {% if request.user.is_student %}
                    <div class="col-md-6 pt-md-0 pt-3"> 
                        <label for="department">מחלקה</label>  
                        {{form.department}}
                    </div>
                {% endif %}
            </div> 
            {% if request.user.is_student %}
                <div class="row py-2">
                    <div class="col-md-6"> 
                        <label for="semester">סמסטר</label> 
                        {{form.semester}}
                    </div>
                    <div class="col-md-6 pt-md-0 pt-3"> 
                        <label for="year">שנת לימודים</label>  
                        {{form.year}}
                    </div>
                </div>
            {% endif %}
    </form>

            <div class="py-3 pb-4 border-bottom"> 
                <button class="btn btn-primary mr-3">Save Changes</button> 
                <a href="{% url 'HomePage:home'%}" class="btn border button">Cancel</a>
                <a href="{% url 'Details:ch-pass' request.user.id %}" class="changePass">שינוי סיסמא</a>

            </div>
            <div class="d-sm-flex align-items-center pt-3" id="deactivate">
                <div> 
                    <b>Deactivate your account</b>
                    <p>Details about your company account and password</p>
                </div>
                <div class="ml-auto"> 
                   <a href="{% url 'Details:delete-user' request.user.id %}" class="btn danger">Delete User</a>
                </div>
            </div>
        </div>
        </div>
{% endblock %}