Estudy_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# TEMPLATE TAGGING

urlpatterns = [
    path("", include("HomePage.urls")),
    path("acoounts/", include("django.contrib.auth.urls")),
    path("register/", include("accounts.urls")),
    path("admin/", admin.site.urls, name="admin-site-url"),
    path("details/", include("DetailsAccount.urls")),
    path("category/", include("category.urls")),
    path("forum/", include("forum.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("youtube/", include("YouTube.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomePage/urls.py
from django.urls import path, include
from . import views


app_name = "HomePage"

urlpatterns = [
    path("", views.indexView.as_view(), name="home"),
    path("about/", views.aboutView.as_view(), name="about"),
    path("Delete/<post_id>", views.deletePost, name="delete-post"),
    path("update/<post_id>", views.updatePost, name="update-post"),
    path("search/", views.searchView.as_view(), name="search-user"),
    path("down/<int:user_id>", views.DownPermissions.as_view(), name="down-per"),
    path("<int:user_id>", views.UpPermissions.as_view(), name="up-per"),
]

YouTube/urls.py
from django.urls import path
from YouTube import views

app_name = "YouTube"

urlpatterns = [
    path("", views.SearchVideoView.as_view(), name="youtube"),
    path("save/<int:video_index>", views.SaveVideoView.as_view(), name="save-video"),
    path(
        "upload/<int:video_index>",
        views.CreateCourseView.as_view(),
        name="create-course",
    ),
    path(
        "videos/<str:course_id>/<str:user_id>/<int:video_index>/",
        views.YouTubeVideoView.as_view(),
        name="yotube-video",
    ),
]

accounts/urls.py
from django.urls import path


from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signUp, name="signup"),
    path("signupStudent/", views.signStudentView.as_view(), name="si-student"),
    path("signupLecture/", views.signLectureView.as_view(), name="si-lecture"),
    # path('login/', views.LogInView.as_view(), name='logIn'),
]

category/urls.py
from django.urls import path
from category import views

app_name = "Category"

urlpatterns = [
    path("<user_id>", views.CategoryView.as_view(), name="cat"),
    path(
        "course/<course_id>/<user_id>", views.HomeWorksView.as_view(), name="homework"
    ),
    path(
        "upload-file/<course_id>/<user_id>", views.UploadFileView.as_view(), name="u-f"
    ),
    path("upload/", views.CreateCourseView.as_view(), name="create-course"),
    path("del/<course_id>", views.deleteCourse, name="delete-course"),
    path("delfile/<course_id>/<hw_id>", views.deleteFile, name="delete-file"),
    path("delVideo/<course_id>/<video_id>", views.deleteVideo, name="delete-video"),
    path("videos/<course_id>/cc", views.VideoView.as_view(), name="videos"),
    path("forumFile/<hw_id>", views.ForumFileView.as_view(), name="forum-file"),
    path("delComment/<int:comment_id>/<hw_id>", views.DeleteComment, name="delete-co"),
]

forum/urls.py
from django.urls import path
from forum import views

app_name = "Forum"

urlpatterns = [
    path("", views.forumView.as_view(), name="forum-main"),
    path("<user_id>", views.forumView.as_view(), name="post-post"),
    path("<user_id>/<post_id>", views.PostComments, name="comment-post"),
    path("delete/<int:post_id>/", views.DeletePost, name="delete-po"),
    path("delComment/<int:comment_id>/", views.DeleteComment, name="delete-co"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

{{student}}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">

  {% block links %}
  {% endblock links %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>{% block page_title %}{% endblock %}</title>
</head>
<style>
    body {
      background-color: aliceblue
  }

  .nav-link {
      display: block;
      padding: .5rem 1rem;
      text-decoration: none;
      transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out;
      color: #000000;
      margin-right: 10px;
      text-transform: uppercase;
      font-weight: 200 !important;
      font-size: 14px
  }

  .navbar-toggler-icon {
      background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255,102,203, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E")
  }

  .navbar-nav .active {
      border-bottom: 4px solid #fff
  }

  .logo {
      margin-bottom: 7px !important
  }

  .navbar {
      padding-top: .5rem;
      padding-bottom: 0px !important
  }

  .profileNav{
    width: 30px;
    height: 30px;
    border-radius: 50%;
    object-fit: cover
  }

  #userName{
    color: blue;
  }
</style>

{% block style %}
{% endblock style %}

<header>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'HomePage:home' %}">
        <img src="{% static 'images/ES.png' %}" width="90" class="logo" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                  {% if user.is_superuser %}
                      <p class="nav-link active" aria-current="page" href="" id="userName"><b>Admin</b></p>
                  {% elif user.is_student %}
                      <p class="nav-link active" aria-current="page" href="" id="userName"><b>Student</b></p>
                  {% elif user.is_lecturer%}
                      <p class="nav-link active" aria-current="page" href="" id="userName"><b>lecturer</b></p>
                  {% endif %}
                  <p class="nav-link active" aria-current="page" href="" id="userName"><b>{{user.username}}</b></p>
                  <a class="nav-link" href="{% url 'HomePage:about' %}"><b>about</b></a>
                  <a class="nav-link" href="{% url 'logout' %}"><b>log out</b></a>
                  <a class="nav-link" href="{% url 'YouTube:youtube' %}"><b>YouTube Search</b></a>

                {% if request.user.is_student %}
                  <a class="nav-link" href="{% url 'Details:d-s' request.user.id %}"><b>Settings</b></a>
                  <a class="nav-link" href="{% url 'Category:cat' request.user.id %}"><b>Category</b></a>
                {% elif request.user.is_lecturer%}
                  <a class="nav-link" href="{% url 'Forum:forum-main'%}"><b>Forum</b></a>
                  <a class="nav-link" href="{% url 'Details:d-l' request.user.id %}"><b>Settings</b></a>
                  <a class="nav-link" href="{% url 'Category:cat' request.user.id %}"><b>Category</b></a>
                  {% else %}
                  <a class="nav-link" href="{% url 'Forum:forum-main'%}"><b>Forum</b></a>
                  <a class="nav-link" href="{% url 'Category:cat' request.user.id %}"><b>Category</b></a>
                  <a class="nav-link" href="/admin"><b>Admin Zone</b></a>
                  <a class="nav-link" href="{% url 'HomePage:search-user' %}"><b>Search User</b></a>
                {% endif %}

                  {% if request.user.imag_profile %}
                      {% comment %} {% if request.user.student.imag_profile %}
                        <img src="{{request.user.student.imag_profile.url}}" class="profileNav"> </a>
                      {% endif %}
                  {% elif request.user.is_lecturer%} {% endcomment %}
                   <img src="{{user.imag_profile.url}}"  class="profileNav"> </a>
                  {% else %}
                    <img src="{% static 'images/defProfile.png' %}"  class="profileNav"> </a>
                  {% endif %}
              {% else %}
              <a class="nav-link" href="{% url 'HomePage:about' %}"><b>about</b></a>
                <a class="nav-link" href="{% url 'accounts:signup' %}"><b>sign up</b></a>
                <a class="nav-link" href="{% url 'login' %}"><b>log in</b></a>
              {% endif %}
              </div>
        </div>
    </div>
</nav>
</header>

<body>
  {% block content %}
  {% endblock content %}

</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script></html>